/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Collection = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'inStock' : IDL.Bool,
  'collection' : Collection,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Float64,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({
  'total' : IDL.Float64,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCollection' : IDL.Func(
      [Collection],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'updateQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Collection = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'inStock' : IDL.Bool,
    'collection' : Collection,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'total' : IDL.Float64,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCollection' : IDL.Func(
        [Collection],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'updateQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };