/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'total' : number, 'items' : Array<CartItem> }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type Collection = string;
export interface Product {
  'id' : ProductId,
  'inStock' : boolean,
  'collection' : Collection,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'price' : number,
}
export type ProductId = bigint;
export interface _SERVICE {
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Cart>,
  'getCollections' : ActorMethod<[], Array<Collection>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCollection' : ActorMethod<[Collection], Array<Product>>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'updateQuantity' : ActorMethod<[ProductId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];